<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Hello Hexlet!</title>
</head>
<body>
<div class="col-lg-8 mx-auto p-4 py-md-5">
    <main>
        <h1 class="text-body-emphasis">Анализатор страниц</h1>
        <%--<p>Javalin + jte</p>--%>
        <input type="text" name="url" value="" placeholder="Ссылка"/>
        <input type="submit" value="Проверить"/>
    </main>
</div>
</body>
</html>